### ISSUE TITLE
Error creating Pipfile

### ISSUE THREAD

**Issue by pacospace** [thoth-station/jupyterlab-requirements#155]
**Describe the bug**
Error creating Pipfile

**To Reproduce**
1. Use JH from Operate first
2. Spawn image called: `ml-prague-workshop:latest` (using jupyterlab-requirement v0.4.1)

**Expected behavior**
No error updating Pipfile in overlays directory.

**Screenshots**
```
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
2021-02-22 15:56:28,227 [141] INFO     jupyterlab_requirements.dependencies_files_handler: path to store dependencies is: 'overlays'
[E 2021-02-22 15:56:28.231 SingleUserLabApp web:1789] Uncaught exception POST /user/fmurdaca@redhat.com/jupyterlab_requirements/file/dependencies?1614009388061 (::ffff:10.128.4.2)
    HTTPServerRequest(protocol='http', host='jupyterhub-opf-jupyterhub.apps.cnv.massopen.cloud', method='POST', uri='/user/fmurdaca@redhat.com/jupyterlab_requirements/file/dependencies?1614009388061', version='HTTP/1.1', remote_ip='::ffff:10.128.4.2')
    Traceback (most recent call last):
      File "/opt/app-root/lib64/python3.8/site-packages/tornado/web.py", line 1702, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/opt/app-root/lib64/python3.8/site-packages/tornado/web.py", line 3173, in wrapper
        return method(self, *args, **kwargs)
      File "/opt/app-root/lib64/python3.8/site-packages/jupyterlab_requirements/dependency_management/dependencies_files_handler.py", line 101, in post
        project.to_files(
      File "/opt/app-root/lib64/python3.8/site-packages/thoth/python/project.py", line 149, in to_files
        with open(pipfile_path or "Pipfile", "w") as pipfile_file:
    FileNotFoundError: [Errno 2] No such file or directory: 'overlays/download-dataset/Pipfile'
```

**Additional context**

**Comment by pacospace** [comment]
Depends-On: https://github.com/thoth-station/jupyterlab-requirements/issues/157
