### ISSUE TITLE
Error updating .thoth.yaml

### ISSUE THREAD

**Issue by pacospace** [thoth-station/jupyterlab-requirements#156]
**Describe the bug**
Error updating .thoth.yaml.

**To Reproduce**
1. Use JH from Operate first
2. Spawn image called: `ml-prague-workshop:latest` (using jupyterlab-requirement v0.4.1)

**Expected behavior**
No errors updating .thoth.yaml.

**Screenshots**
```
1-02-22 15:56:28.346 SingleUserLabApp web:1789] Uncaught exception PUT /user/fmurdaca@redhat.com/jupyterlab_requirements/thoth/config?1614009388289 (::ffff:10.128.4.2)
    HTTPServerRequest(protocol='http', host='jupyterhub-opf-jupyterhub.apps.cnv.massopen.cloud', method='PUT', uri='/user/fmurdaca@redhat.com/jupyterlab_requirements/thoth/config?1614009388289', version='HTTP/1.1', remote_ip='::ffff:10.128.4.2')
    Traceback (most recent call last):
      File "/opt/app-root/lib64/python3.8/site-packages/tornado/web.py", line 1702, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/opt/app-root/lib64/python3.8/site-packages/tornado/web.py", line 3173, in wrapper
        return method(self, *args, **kwargs)
      File "/opt/app-root/lib64/python3.8/site-packages/jupyterlab_requirements/dependency_management/thoth_config_handler.py", line 78, in put
        configuration.set_runtime_environment(
      File "/opt/app-root/lib64/python3.8/site-packages/thamos/config.py", line 328, in set_runtime_environment
        existing = self.get_runtime_environment(runtime_environment["name"])
      File "/opt/app-root/lib64/python3.8/site-packages/thamos/config.py", line 344, in get_runtime_environment
        content = self.content
      File "/opt/app-root/lib64/python3.8/site-packages/thamos/config.py", line 162, in content
        self.load_config()
      File "/opt/app-root/lib64/python3.8/site-packages/thamos/config.py", line 226, in load_config
        with workdir(config.CONFIG_NAME):
      File "/usr/lib64/python3.8/contextlib.py", line 113, in __enter__
        return next(self.gen)
      File "/opt/app-root/lib64/python3.8/site-packages/thamos/utils.py", line 52, in workdir
        raise NoProjectDirError(
    thamos.exceptions.NoProjectDirError: No .thoth.yaml found in the current directory '/opt/app-root/src/overlays' or in any of its parent directories, you can generate it using '/opt/app-root/bin/jupyter-labhub config'
```

**Additional context**

**Comment by pacospace** [comment]
Depends-On: https://github.com/thoth-station/jupyterlab-requirements/issues/157
