### ISSUE TITLE
Handle paths differently to avoid errors in the cluster when files need to be stored (e.g. overlays)

### ISSUE THREAD

**Issue by pacospace** [thoth-station/jupyterlab-requirements#157]
**Describe the bug**
overlays/ directory is stored outside the git project.

**To Reproduce**
1. Use JH from Operate first
2. Spawn image called: `ml-prague-workshop:latest` (using jupyterlab-requirement v0.4.1)

**Expected behavior**
The overlays directory is updated correctly at the path inside git repo

**Screenshots**

**Additional context**

**Comment by pacospace** [comment]
```
[E 2021-02-25 21:41:31.818 SingleUserLabApp web:1789] Uncaught exception POST /user/fmurdaca@redhat.com/jupyterlab_requirements/file/dependencies?1614289276174 (::ffff:10.128.4.2)
    HTTPServerRequest(protocol='http', host='jupyterhub-opf-jupyterhub.apps.cnv.massopen.cloud', method='POST', uri='/user/fmurdaca@redhat.com/jupyterlab_requirements/file/dependencies?1614289276174', version='HTTP/1.1', remote_ip='::ffff:10.128.4.2')
    Traceback (most recent call last):
      File "/opt/app-root/lib64/python3.8/site-packages/tornado/web.py", line 1702, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/opt/app-root/lib64/python3.8/site-packages/tornado/web.py", line 3173, in wrapper
        return method(self, *args, **kwargs)
      File "/opt/app-root/lib64/python3.8/site-packages/jupyterlab_requirements/dependency_management/dependencies_files_handler.py", line 84, in post
        git_root = p.parts[0]
    IndexError: tuple index out of range
    ```
