### ISSUE TITLE
do we want backcompatibility with python 3.6?

### ISSUE THREAD

**Issue by pacospace** [thoth-station/jupyterlab-requirements#205]
List of issues to be considered, in case we need to support users with python 3.6 in the future:

- changes in subprocess
```
[E 2021-03-11 10:35:18.546 ServerApp] Uncaught exception POST /jupyterlab_requirements/kernel/packages?1615455318540 (::1)
    HTTPServerRequest(protocol='http', host='localhost:8888', method='POST', uri='/jupyterlab_requirements/kernel/packages?1615455318540', version='HTTP/1.1', remote_ip='::1')
    Traceback (most recent call last):
      File "/home/fmurdaca/.local/share/virtualenvs/jupyterlab-requirements-wZBGhmnk/lib/python3.6/site-packages/tornado/web.py", line 1702, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/fmurdaca/.local/share/virtualenvs/jupyterlab-requirements-wZBGhmnk/lib/python3.6/site-packages/tornado/web.py", line 3173, in wrapper
        return method(self, *args, **kwargs)
      File "/home/fmurdaca/work/aicoe/jupyterlab-requirements/jupyterlab_requirements/dependency_management/dependencies_discover_handler.py", line 49, in post
        cwd=complete_path
      File "/usr/lib64/python3.6/subprocess.py", line 423, in run
        with Popen(*popenargs, **kwargs) as process:
    TypeError: __init__() got an unexpected keyword argument 'capture_output'
```

- changes in traitlets packages (fundamental transitive dependency of ipykernel and other jupyter tools)

traitlets == 4.3.2, because above it requires minimum python 3.7, but traitlets reached >5.*

**Comment by pacospace** [comment]
I will close this issue, is someone from community is interested, we will check on resources and if we can help there.
