### ISSUE TITLE
KeyError: 'runtime_environment' when using `horus lock`

### ISSUE THREAD

**Issue by MichaelClifford** [thoth-station/jupyterlab-requirements#538]
**Describe the bug**

`horus lock notebooks/Untitled.ipynb --kernel-name test --pipenv` throws a `KeyError: 'runtime_environment'` with version: 0.11.0 on the jupyter lab image.

Additional Info:
Horus (jupyterlab-requirements CLI) version: 0.11.0
Thamos Client version: 1.17.0
Thoth API N/A: N/A

**To Reproduce**
1. Open Jupyter Lab with jupyterlab-requirements CLI version: 0.11.0
2. Create a new notebook in `notebooks/Untitled.ipynb `
3. run `horus requirements notebooks/Untitled.ipynb --add "pandas == 1.3.0"`
3. run `horus lock notebooks/Untitled.ipynb --kernel-name test --pipenv` 
4. See error:
```
Resolution engine used: pipenv
Kernel name is: test
Traceback (most recent call last):
  File "/opt/app-root/bin/horus", line 8, in <module>
    sys.exit(cli())
  File "/opt/app-root/lib64/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/opt/app-root/lib64/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/opt/app-root/lib64/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/app-root/lib64/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/app-root/lib64/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/opt/app-root/lib64/python3.8/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/opt/app-root/lib64/python3.8/site-packages/jupyterlab_requirements/cli.py", line 699, in lock
    click.echo(f"runtime environment used: {results['runtime_environment']}")
KeyError: 'runtime_environment'
```
see same behavior with resolution engine thoth

**Expected behavior**
horus lock runs correctly and I'm able to use the pipelock to define the environment for my notebook. 

**Environment information**
Describe the environment from where you are using the extension:
 - jupyterlab version: 3.0.14
 - jupyterlab-requirements version: 0.11.0
 - Installation source: PyPI
 - Operating system: RHEL
 - Environment type: JupyterHub spawned image

**Comment by pacospace** [comment]
Thanks for the issue @MichaelClifford!!

I realized there is an issue in the image we are using @MichaelClifford with Elyra, I opened https://github.com/opendatahub-io/s2i-lab-elyra/pull/35 to solve that and I will take care of this soon!

**Comment by pacospace** [comment]
I tested new elyra image, but it turns out this error is only on the CLI, I fixed it in the linked Pull Request.
